name: 'Luxury Brand Partner Test on Develop'
on:
  push:
  pull_request:
    #branches:    
     # - develop

jobs:
  ubuntu-job:
    name: 'Getting Ubuntu images for test execution'
    runs-on: ubuntu-latest  # Can be self-hosted runner also
    steps:

      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}      

      - name: 'Checkout the repository'
        uses:  actions/checkout@v2
        
      - name: Replace image in config
        uses: ./.github/actions/replace
        with:
            files: Config.properties
            replacements: 'devurl: https://pro.luxbp.com/'          
        
      - name: 'Clean install'
        run:   mvn clean install -DskipTests

      - name: 'Compiling automation test cases'
        run:   mvn compile              

      - name: 'Executing Test file'
        run:   mvn test -P luxbp-dev
